version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - pgData:/data/postgres
    env_file:
      - ./.env

volumes:
  pgData:
